// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyFHBVTwjPHiUx79YBKe80MXkZHbcevuQ',
    appId: '1:260906210942:web:8ed7f92e1e2c6a03d62a2f',
    messagingSenderId: '260906210942',
    projectId: 'ticket--cinema',
    authDomain: 'ticket--cinema.firebaseapp.com',
    storageBucket: 'ticket--cinema.appspot.com',
    measurementId: 'G-F3WPDXB3B9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCevGhS9Hc2eqIjZeRdzgbBW5Ud3StjAfc',
    appId: '1:260906210942:android:a2b84fe316b3486bd62a2f',
    messagingSenderId: '260906210942',
    projectId: 'ticket--cinema',
    storageBucket: 'ticket--cinema.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzQYzGhHuNGr4Guhh7JkrqDWgPoiERYxw',
    appId: '1:260906210942:ios:107da002917f97e3d62a2f',
    messagingSenderId: '260906210942',
    projectId: 'ticket--cinema',
    storageBucket: 'ticket--cinema.appspot.com',
    iosClientId: '260906210942-2n264gqfga6nthoivnbqvoouf0llb2qr.apps.googleusercontent.com',
    iosBundleId: 'com.example.cinemaTicket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzQYzGhHuNGr4Guhh7JkrqDWgPoiERYxw',
    appId: '1:260906210942:ios:107da002917f97e3d62a2f',
    messagingSenderId: '260906210942',
    projectId: 'ticket--cinema',
    storageBucket: 'ticket--cinema.appspot.com',
    iosClientId: '260906210942-2n264gqfga6nthoivnbqvoouf0llb2qr.apps.googleusercontent.com',
    iosBundleId: 'com.example.cinemaTicket',
  );
}
