import '../model/seat_model.dart';

final seatLayout = SeatLayoutModel(
  rows: 14, cols: 12,
  takedSeat: [
    {'row': 5, 'col': 2},
    {'row': 8, 'col': 2},
    {'row': 8, 'col': 3},
    {'row': 8, 'col': 8},
    {'row': 8, 'col': 10},
    {'row': 12, 'col': 11},
    {'row': 12, 'col': 10},
    {'row': 12, 'col': 9},
    {'row': 11, 'col': 7},
    {'row': 10, 'col': 7},
    {'row': 11, 'col': 7},
    {'row': 13, 'col': 11},
    {'row': 13, 'col': 11},
    {'row': 13, 'col': 11},
    {'row': 13, 'col': 11},
    {'row': 13, 'col': 11},
    {'row': 13, 'col': 10},
    {'row': 0, 'col': 6},
    {'row': 13, 'col': 5},
    {'row': 12, 'col': 5},
    {'row': 12, 'col': 5},
    {'row': 13, 'col': 5},
    {'row': 13, 'col': 5},
    {'row': 13, 'col': 5},
    {'row': 13, 'col': 5},
    {'row': 13, 'col': 2},
    {'row': 8, 'col': 4},
    {'row': 8, 'col': 5},
    {'row': 8, 'col': 6},
    {'row': 3, 'col': 4},
    {'row': 7, 'col': 0},
    {'row': 6, 'col': 4},
    {'row': 6, 'col': 4},
    {'row': 6, 'col': 5},
    {'row': 14, 'col': 12},
    {'row': 14, 'col': 11},
    {'row': 14, 'col': 10},
    {'row': 14, 'col': 9},
    {'row': 14, 'col': 8},
    {'row': 14, 'col': 7},
    {'row': 13, 'col': 7},
    {'row': 13, 'col': 8},
    {'row': 13, 'col': 9},
    {'row': 13, 'col': 12},
    {'row': 12, 'col': 12},
    {'row': 10, 'col': 12},
    {'row': 11, 'col': 12},
    {'row': 11, 'col': 11},
    {'row': 11, 'col': 9},
    {'row': 11, 'col': 8},
    {'row': 12, 'col': 8},
    {'row': 12, 'col': 7},
    {'row': 11, 'col': 10},
    {'row': 10, 'col': 11},
    {'row': 14, 'col': 6},
    {'row': 14, 'col': 5},
    {'row': 14, 'col': 4},
    {'row': 14, 'col': 2},
  ],
  //! for future when we add mor than one cinema and seat type cinema
  /*
  // gapIndex: [
  //   {''row'': 1, ''col'': 2},
  //   {''row'': 1, ''col'': 3},
  //   {''row'': 1, ''col'': 4},
  //   {''row'': 1, ''col'': 5},
  //   {''row'': 1, ''col'': 6},
  //   {''row'': 2, ''col'': 3},
  //   {''row'': 2, ''col'': 4},
  //   {''row'': 2, ''col'': 5},
  //   {''row'': 2, ''col'': 6},
  //   {''row'': 3, ''col'': 4},
  //   {''row'': 3, ''col'': 5},
  //   {''row'': 3, ''col'': 6},
  //   {''row'': 4, ''col'': 5},
  //   {''row'': 4, ''col'': 6},
  //   {''row'': 5, ''col'': 6},
  // ], 
  ? 'col' > 'row'
  // gapIndex: [
  //   {''row'': 1, ''col'': 1},
  //   {''row'': 1, ''col'': 2},
  //   {''row'': 1, ''col'': 3},
  //   {''row'': 1, ''col'': 4},
  //   {''row'': 1, ''col'': 5},
  //   {''row'': 2, ''col'': 1},
  //   {''row'': 2, ''col'': 2},
  //   {''row'': 2, ''col'': 3},
  //   {''row'': 2, ''col'': 4},
  //   {''row'': 3, ''col'': 1},
  //   {''row'': 3, ''col'': 2},
  //   {''row'': 3, ''col'': 3},
  //   {''row'': 4, ''col'': 1},
  //   {''row'': 4, ''col'': 2},
  //   {''row'': 5, ''col'': 1},
  // ],
  ? 'col' < 5 - 'row'
  */
);
